# frontend/Makefile

.PHONY: install dev lint test typecheck

install:
	pnpm install

dev:
	pnpm run dev

lint:
	pnpm run lint

typecheck:
	pnpm run typecheck

test:
	pnpm run test

build:
	pnpm nuxi generate  # Mode statique pour Netlify