[build]
  base = ""
  command = "npm install -g pnpm && pnpm install --filter @shared/ui-core && pnpm --filter @shared/ui-core run build && cd frontend && pnpm install && NUXT_PUBLIC_API_BASE=https://mla-backend-ewds.onrender.com pnpm run generate"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "22"
  NUXT_PUBLIC_API_BASE = "https://mla-backend-ewds.onrender.com"

[[redirects]]
  # Important pour Nuxt en mode SPA/Statique sur Netlify
  from = "/*"
  to = "/index.html"
  status = 200