"""add_serie_id_to_planning

Revision ID: 1c6c5996c3a2
Revises: f15f3d7ac637
Create Date: 2026-03-24 17:06:31.393428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c6c5996c3a2'
down_revision: Union[str, Sequence[str], None] = 'f15f3d7ac637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_organisationicc_deleted_at'), table_name='t_organisationicc')
    op.drop_index(op.f('ix_t_organisationicc_nom'), table_name='t_organisationicc')
    op.drop_table('t_organisationicc')
    op.add_column('t_planningservice', sa.Column('serie_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_t_planningservice_serie_id'), 't_planningservice', ['serie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_planningservice_serie_id'), table_name='t_planningservice')
    op.drop_column('t_planningservice', 'serie_id')
    op.create_table('t_organisationicc',
    sa.Column('nom', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('t_organisationicc_pkey'))
    )
    op.create_index(op.f('ix_t_organisationicc_nom'), 't_organisationicc', ['nom'], unique=True)
    op.create_index(op.f('ix_t_organisationicc_deleted_at'), 't_organisationicc', ['deleted_at'], unique=False)
    # ### end Alembic commands ###
