"""

Revision ID: 387bf6be9538
Revises: 
Create Date: 2026-02-21 00:16:35.234758

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '387bf6be9538'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
