"""

Revision ID: 46913fa5fc89
Revises: 88ac551b6b93
Create Date: 2026-02-27 18:41:21.117713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46913fa5fc89'
down_revision: Union[str, Sequence[str], None] = '88ac551b6b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('t_ministere_campus_id_fkey'), 't_ministere', type_='foreignkey')
    op.drop_column('t_ministere', 'campus_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_ministere', sa.Column('campus_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('t_ministere_campus_id_fkey'), 't_ministere', 't_campus', ['campus_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
