"""

Revision ID: 6d98d29545c6
Revises: 387bf6be9538
Create Date: 2026-02-21 00:34:01.477070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6d98d29545c6'
down_revision: Union[str, Sequence[str], None] = '387bf6be9538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_categorierole',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('t_organisationicc',
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_organisationicc_deleted_at'), 't_organisationicc', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_t_organisationicc_nom'), 't_organisationicc', ['nom'], unique=True)
    op.create_table('t_permission',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_permission_code'), 't_permission', ['code'], unique=True)
    op.create_table('t_revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_revoked_tokens_jti'), 't_revoked_tokens', ['jti'], unique=True)
    op.create_table('t_role',
    sa.Column('libelle', sa.Enum('ADMIN', 'RESPONSABLE_MLA', 'MEMBRE_MLA', name='rolename'), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle'),
    sa.UniqueConstraint('libelle')
    )
    op.create_table('t_statutaffectation',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('t_statutplanning',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('t_typeresponsabilite',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('t_pays',
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('organisation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['t_organisationicc.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_pays_code'), 't_pays', ['code'], unique=False)
    op.create_index(op.f('ix_t_pays_deleted_at'), 't_pays', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_t_pays_nom'), 't_pays', ['nom'], unique=True)
    op.create_table('t_role_permission',
    sa.Column('role_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permission_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['t_permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['t_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('t_rolecompetence',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('categorie_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_code'], ['t_categorierole.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('t_campus',
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('ville', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('pays_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['pays_id'], ['t_pays.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_campus_deleted_at'), 't_campus', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_t_campus_nom'), 't_campus', ['nom'], unique=False)
    op.create_table('t_ministere',
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('date_creation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('campus_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['t_campus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_ministere_deleted_at'), 't_ministere', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_t_ministere_nom'), 't_ministere', ['nom'], unique=True)
    op.create_table('t_activite',
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=False),
    sa.Column('lieu', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('campus_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ministere_organisateur_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['t_campus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ministere_organisateur_id'], ['t_ministere.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_activite_deleted_at'), 't_activite', ['deleted_at'], unique=False)
    op.create_table('t_equipe',
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ministere_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['ministere_id'], ['t_ministere.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_pole',
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('ministere_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['ministere_id'], ['t_ministere.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_pole_deleted_at'), 't_pole', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_t_pole_nom'), 't_pole', ['nom'], unique=False)
    op.create_table('t_membre',
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('telephone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_inscription', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('campus_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ministere_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pole_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['t_campus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ministere_id'], ['t_ministere.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pole_id'], ['t_pole.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_membre_campus_id'), 't_membre', ['campus_id'], unique=False)
    op.create_index(op.f('ix_t_membre_deleted_at'), 't_membre', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_t_membre_ministere_id'), 't_membre', ['ministere_id'], unique=False)
    op.create_index(op.f('ix_t_membre_nom'), 't_membre', ['nom'], unique=False)
    op.create_index(op.f('ix_t_membre_pole_id'), 't_membre', ['pole_id'], unique=False)
    op.create_table('t_planningservice',
    sa.Column('statut_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activite_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activite_id'], ['t_activite.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['statut_code'], ['t_statutplanning.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_planningservice_activite_id'), 't_planningservice', ['activite_id'], unique=False)
    op.create_index(op.f('ix_t_planningservice_statut_code'), 't_planningservice', ['statut_code'], unique=False)
    op.create_table('t_equipe_membre',
    sa.Column('equipe_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('membre_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['equipe_id'], ['t_equipe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membre_id'], ['t_membre.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('equipe_id', 'membre_id')
    )
    op.create_table('t_indisponibilite',
    sa.Column('date_debut', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_fin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('motif', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('validee', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('membre_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['t_membre.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_membre_role',
    sa.Column('membre_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('niveau', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['t_membre.id'], ),
    sa.ForeignKeyConstraint(['role_code'], ['t_rolecompetence.code'], ),
    sa.PrimaryKeyConstraint('membre_id', 'role_code')
    )
    op.create_table('t_responsabilite',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_debut', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_fin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('type_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('membre_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ministere_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pole_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activite_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['activite_id'], ['t_activite.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membre_id'], ['t_membre.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ministere_id'], ['t_ministere.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pole_id'], ['t_pole.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_code'], ['t_typeresponsabilite.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_slot',
    sa.Column('planning_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nom_creneau', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=False),
    sa.Column('nb_personnes_requis', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['planning_id'], ['t_planningservice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_utilisateur',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('membre_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['membre_id'], ['t_membre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membre_id'),
    sa.UniqueConstraint('membre_id')
    )
    op.create_table('t_affectation',
    sa.Column('slot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('membre_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('statut_affectation_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('presence_confirmee', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['t_membre.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['t_slot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['statut_affectation_code'], ['t_statutaffectation.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_affectation_role',
    sa.Column('dateDebut', sa.Date(), nullable=True),
    sa.Column('dateFin', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('utilisateur_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['t_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['t_utilisateur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_affectation_contexte',
    sa.Column('voix_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('affectation_role_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ministere_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pole_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activite_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['activite_id'], ['t_activite.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['affectation_role_id'], ['t_affectation_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ministere_id'], ['t_ministere.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pole_id'], ['t_pole.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_affectation_contexte')
    op.drop_table('t_affectation_role')
    op.drop_table('t_affectation')
    op.drop_table('t_utilisateur')
    op.drop_table('t_slot')
    op.drop_table('t_responsabilite')
    op.drop_table('t_membre_role')
    op.drop_table('t_indisponibilite')
    op.drop_table('t_equipe_membre')
    op.drop_index(op.f('ix_t_planningservice_statut_code'), table_name='t_planningservice')
    op.drop_index(op.f('ix_t_planningservice_activite_id'), table_name='t_planningservice')
    op.drop_table('t_planningservice')
    op.drop_index(op.f('ix_t_membre_pole_id'), table_name='t_membre')
    op.drop_index(op.f('ix_t_membre_nom'), table_name='t_membre')
    op.drop_index(op.f('ix_t_membre_ministere_id'), table_name='t_membre')
    op.drop_index(op.f('ix_t_membre_deleted_at'), table_name='t_membre')
    op.drop_index(op.f('ix_t_membre_campus_id'), table_name='t_membre')
    op.drop_table('t_membre')
    op.drop_index(op.f('ix_t_pole_nom'), table_name='t_pole')
    op.drop_index(op.f('ix_t_pole_deleted_at'), table_name='t_pole')
    op.drop_table('t_pole')
    op.drop_table('t_equipe')
    op.drop_index(op.f('ix_t_activite_deleted_at'), table_name='t_activite')
    op.drop_table('t_activite')
    op.drop_index(op.f('ix_t_ministere_nom'), table_name='t_ministere')
    op.drop_index(op.f('ix_t_ministere_deleted_at'), table_name='t_ministere')
    op.drop_table('t_ministere')
    op.drop_index(op.f('ix_t_campus_nom'), table_name='t_campus')
    op.drop_index(op.f('ix_t_campus_deleted_at'), table_name='t_campus')
    op.drop_table('t_campus')
    op.drop_table('t_rolecompetence')
    op.drop_table('t_role_permission')
    op.drop_index(op.f('ix_t_pays_nom'), table_name='t_pays')
    op.drop_index(op.f('ix_t_pays_deleted_at'), table_name='t_pays')
    op.drop_index(op.f('ix_t_pays_code'), table_name='t_pays')
    op.drop_table('t_pays')
    op.drop_table('t_typeresponsabilite')
    op.drop_table('t_statutplanning')
    op.drop_table('t_statutaffectation')
    op.drop_table('t_role')
    op.drop_index(op.f('ix_t_revoked_tokens_jti'), table_name='t_revoked_tokens')
    op.drop_table('t_revoked_tokens')
    op.drop_index(op.f('ix_t_permission_code'), table_name='t_permission')
    op.drop_table('t_permission')
    op.drop_index(op.f('ix_t_organisationicc_nom'), table_name='t_organisationicc')
    op.drop_index(op.f('ix_t_organisationicc_deleted_at'), table_name='t_organisationicc')
    op.drop_table('t_organisationicc')
    op.drop_table('t_categorierole')
    # ### end Alembic commands ###
