"""

Revision ID: 88ac551b6b93
Revises: 6d98d29545c6
Create Date: 2026-02-24 01:35:19.787767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ac551b6b93'
down_revision: Union[str, Sequence[str], None] = '6d98d29545c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_membre_campus_link',
    sa.Column('membre_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campus_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['t_campus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membre_id'], ['t_membre.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membre_id', 'campus_id')
    )
    op.create_table('t_membre_ministere_link',
    sa.Column('membre_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ministere_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['t_membre.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ministere_id'], ['t_ministere.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membre_id', 'ministere_id')
    )
    op.create_table('t_membre_pole_link',
    sa.Column('membre_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pole_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['t_membre.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pole_id'], ['t_pole.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membre_id', 'pole_id')
    )
    op.drop_index(op.f('ix_t_membre_campus_id'), table_name='t_membre')
    op.drop_index(op.f('ix_t_membre_ministere_id'), table_name='t_membre')
    op.drop_index(op.f('ix_t_membre_pole_id'), table_name='t_membre')
    op.drop_constraint(op.f('t_membre_campus_id_fkey'), 't_membre', type_='foreignkey')
    op.drop_constraint(op.f('t_membre_ministere_id_fkey'), 't_membre', type_='foreignkey')
    op.drop_constraint(op.f('t_membre_pole_id_fkey'), 't_membre', type_='foreignkey')
    op.drop_column('t_membre', 'campus_id')
    op.drop_column('t_membre', 'ministere_id')
    op.drop_column('t_membre', 'pole_id')
    op.create_index(op.f('ix_t_planningservice_deleted_at'), 't_planningservice', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_planningservice_deleted_at'), table_name='t_planningservice')
    op.add_column('t_membre', sa.Column('pole_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('t_membre', sa.Column('ministere_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('t_membre', sa.Column('campus_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('t_membre_pole_id_fkey'), 't_membre', 't_pole', ['pole_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('t_membre_ministere_id_fkey'), 't_membre', 't_ministere', ['ministere_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('t_membre_campus_id_fkey'), 't_membre', 't_campus', ['campus_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_t_membre_pole_id'), 't_membre', ['pole_id'], unique=False)
    op.create_index(op.f('ix_t_membre_ministere_id'), 't_membre', ['ministere_id'], unique=False)
    op.create_index(op.f('ix_t_membre_campus_id'), 't_membre', ['campus_id'], unique=False)
    op.drop_table('t_membre_pole_link')
    op.drop_table('t_membre_ministere_link')
    op.drop_table('t_membre_campus_link')
    # ### end Alembic commands ###
