"""

Revision ID: 8b92d08a7514
Revises: 7c744d4b3817
Create Date: 2026-03-16 00:17:05.168282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b92d08a7514'
down_revision: Union[str, Sequence[str], None] = '7c744d4b3817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_organisationicc_deleted_at'), table_name='t_organisationicc')
    op.drop_index(op.f('ix_t_organisationicc_nom'), table_name='t_organisationicc')
    op.drop_table('t_organisationicc')
    op.drop_index(op.f('ix_indisponibilite_ministere_id'), table_name='t_indisponibilite')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_indisponibilite_ministere_id'), 't_indisponibilite', ['ministere_id'], unique=False)
    op.create_table('t_organisationicc',
    sa.Column('nom', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('t_organisationicc_pkey'))
    )
    op.create_index(op.f('ix_t_organisationicc_nom'), 't_organisationicc', ['nom'], unique=True)
    op.create_index(op.f('ix_t_organisationicc_deleted_at'), 't_organisationicc', ['deleted_at'], unique=False)
    # ### end Alembic commands ###
