"""add_ministere_id_and_description_to_categorie_role

Revision ID: 9a3b08e0c005
Revises: a8c3f5d2e1b7
Create Date: 2026-03-15 00:52:35.706476

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3b08e0c005'
down_revision: Union[str, Sequence[str], None] = 'a8c3f5d2e1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_categorierole', sa.Column('ministere_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('t_categorierole', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 't_categorierole', 't_ministere', ['ministere_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_categorierole', type_='foreignkey')
    op.drop_column('t_categorierole', 'description')
    op.drop_column('t_categorierole', 'ministere_id')
    # ### end Alembic commands ###
