# data_extra.py — données supplémentaires seed (membres, indisponibilités)
# Ce fichier complète data.py ; les TypedDicts sont importés depuis data.py.
from typing import List, Optional, TypedDict

from .data import MembreInfo


class IndisponibiliteData(TypedDict):
    """Indisponibilité à insérer en seed."""

    membre_email: str
    date_debut: str
    date_fin: str
    motif: Optional[str]
    validee: bool


# ---------------------------------------------------------------------------
# 57 membres supplémentaires (sans compte Utilisateur)
# Répartis sur Paris / Toulouse / les deux campus
# ---------------------------------------------------------------------------
CAMPUS_PARIS_LIST = ["Campus Paris"]
CAMPUS_TOULOUSE_LIST = ["Campus Toulouse"]
CAMPUS_BOTH_LIST = ["Campus Paris", "Campus Toulouse"]

MEMBRES_SUPPLEMENTAIRES: List[MembreInfo] = [
    # ── Louange et Adoration — Paris (10) ──────────────────────────────────
    {
        "nom": "Leclerc",
        "prenom": "Marie",
        "email": "marie.leclerc@exemple.com",
        "roles": ["SOPRANO"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Louange et Adoration"],
        "pole_names": ["Chorale"],
    },
    {
        "nom": "Fontaine",
        "prenom": "Claire",
        "email": "claire.fontaine@exemple.com",
        "roles": ["SOPRANO"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Louange et Adoration"],
        "pole_names": ["Chorale"],
    },
    {
        "nom": "Martin",
        "prenom": "Sophie",
        "email": "sophie.martin@exemple.com",
        "roles": ["ALTO"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Louange et Adoration"],
        "pole_names": ["Chorale"],
    },
    {
        "nom": "Durand",
        "prenom": "Isabelle",
        "email": "isabelle.durand@exemple.com",
        "roles": ["ALTO"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Louange et Adoration"],
        "pole_names": ["Chorale"],
    },
    {
        "nom": "Bernard",
        "prenom": "Pierre",
        "email": "pierre.bernard@exemple.com",
        "roles": ["TENOR"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Louange et Adoration"],
        "pole_names": ["Chorale"],
    },
    {
        "nom": "Leblanc",
        "prenom": "David",
        "email": "david.leblanc@exemple.com",
        "roles": ["TENOR"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Louange et Adoration"],
        "pole_names": ["Chorale"],
    },
    {
        "nom": "Petit",
        "prenom": "Lucie",
        "email": "lucie.petit@exemple.com",
        "roles": ["PIANO"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Louange et Adoration"],
        "pole_names": ["Musiciens"],
    },
    {
        "nom": "Garnier",
        "prenom": "Mathieu",
        "email": "mathieu.garnier@exemple.com",
        "roles": ["BATTERIE"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Louange et Adoration"],
        "pole_names": ["Musiciens"],
    },
    {
        "nom": "Poiret",
        "prenom": "Josephine",
        "email": "josephine.poiret@exemple.com",
        "roles": ["SOPRANO"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Louange et Adoration"],
        "pole_names": ["Chorale"],
    },
    {
        "nom": "Andre",
        "prenom": "Christophe",
        "email": "christophe.andre@exemple.com",
        "roles": ["PIANO"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Louange et Adoration"],
        "pole_names": ["Musiciens"],
    },
    # ── Louange et Adoration — Toulouse (6) ────────────────────────────────
    {
        "nom": "Rousseau",
        "prenom": "Amandine",
        "email": "amandine.rousseau@exemple.com",
        "roles": ["SOPRANO"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Louange et Adoration"],
        "pole_names": ["Chorale"],
    },
    {
        "nom": "Morel",
        "prenom": "Florent",
        "email": "florent.morel@exemple.com",
        "roles": ["TENOR"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Louange et Adoration"],
        "pole_names": ["Chorale"],
    },
    {
        "nom": "Roux",
        "prenom": "Camille",
        "email": "camille.roux@exemple.com",
        "roles": ["ALTO"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Louange et Adoration"],
        "pole_names": ["Chorale"],
    },
    {
        "nom": "Lambert",
        "prenom": "Theo",
        "email": "theo.lambert@exemple.com",
        "roles": ["PIANO"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Louange et Adoration"],
        "pole_names": ["Musiciens"],
    },
    {
        "nom": "Girard",
        "prenom": "Nadia",
        "email": "nadia.girard@exemple.com",
        "roles": ["SOPRANO"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Louange et Adoration"],
        "pole_names": ["Chorale"],
    },
    {
        "nom": "Chevalier",
        "prenom": "Antoine",
        "email": "antoine.chevalier@exemple.com",
        "roles": ["BATTERIE"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Louange et Adoration"],
        "pole_names": ["Musiciens"],
    },
    # ── Technique — Paris (3) ───────────────────────────────────────────────
    {
        "nom": "Bonnet",
        "prenom": "Marc",
        "email": "marc.bonnet@exemple.com",
        "roles": ["SON"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Technique"],
        "pole_names": ["Son et Lumière"],
    },
    {
        "nom": "Fournier",
        "prenom": "Lucas",
        "email": "lucas.fournier@exemple.com",
        "roles": ["LUMIERE"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Technique"],
        "pole_names": ["Son et Lumière"],
    },
    {
        "nom": "Perrin",
        "prenom": "Kevin",
        "email": "kevin.perrin@exemple.com",
        "roles": ["VIDEO"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Technique"],
        "pole_names": ["Vidéo et Streaming"],
    },
    # ── Technique — Toulouse (3) ────────────────────────────────────────────
    {
        "nom": "Mercier",
        "prenom": "Thomas",
        "email": "thomas.mercier@exemple.com",
        "roles": ["SON"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Technique"],
        "pole_names": ["Son et Lumière"],
    },
    {
        "nom": "Simon",
        "prenom": "Elisa",
        "email": "elisa.simon@exemple.com",
        "roles": ["LUMIERE"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Technique"],
        "pole_names": ["Son et Lumière"],
    },
    {
        "nom": "Guillot",
        "prenom": "Raphael",
        "email": "raphael.guillot@exemple.com",
        "roles": ["VIDEO"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Technique"],
        "pole_names": ["Vidéo et Streaming"],
    },
    # ── Accueil — Paris (5) ─────────────────────────────────────────────────
    {
        "nom": "Diallo",
        "prenom": "Fatou",
        "email": "fatou.diallo@exemple.com",
        "roles": ["HOTE_ACCUEIL"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Accueil"],
        "pole_names": ["Ushers"],
    },
    {
        "nom": "Coulibaly",
        "prenom": "Ibrahim",
        "email": "ibrahim.coulibaly@exemple.com",
        "roles": ["HOTE_ACCUEIL"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Accueil"],
        "pole_names": ["Ushers"],
    },
    {
        "nom": "Bah",
        "prenom": "Yasmina",
        "email": "yasmina.bah@exemple.com",
        "roles": ["HOTE_ACCUEIL"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Accueil"],
        "pole_names": ["Ushers"],
    },
    {
        "nom": "Aubert",
        "prenom": "Cecile",
        "email": "cecile.aubert@exemple.com",
        "roles": ["HOTE_ACCUEIL"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Accueil"],
        "pole_names": ["Ushers"],
    },
    {
        "nom": "Kone",
        "prenom": "Moussa",
        "email": "moussa.kone@exemple.com",
        "roles": ["HOTE_ACCUEIL"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Accueil"],
        "pole_names": ["Ushers"],
    },
    # ── Accueil — Toulouse (4) ──────────────────────────────────────────────
    {
        "nom": "Ndiaye",
        "prenom": "Rose",
        "email": "rose.ndiaye@exemple.com",
        "roles": ["HOTE_ACCUEIL"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Accueil"],
        "pole_names": ["Ushers"],
    },
    {
        "nom": "Toure",
        "prenom": "Emmanuel",
        "email": "emmanuel.toure@exemple.com",
        "roles": ["HOTE_ACCUEIL"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Accueil"],
        "pole_names": ["Ushers"],
    },
    {
        "nom": "Traore",
        "prenom": "Aicha",
        "email": "aicha.traore@exemple.com",
        "roles": ["HOTE_ACCUEIL"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Accueil"],
        "pole_names": ["Ushers"],
    },
    {
        "nom": "Kodjovi",
        "prenom": "Seraphin",
        "email": "seraphin.kodjovi@exemple.com",
        "roles": ["HOTE_ACCUEIL"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Accueil"],
        "pole_names": ["Ushers"],
    },
    # ── Jeunesse — Paris (4) ────────────────────────────────────────────────
    {
        "nom": "Renard",
        "prenom": "Nathan",
        "email": "nathan.renard@exemple.com",
        "roles": ["ANIMATEUR_JEUNESSE"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Jeunesse"],
        "pole_names": ["Ados"],
    },
    {
        "nom": "Dupuis",
        "prenom": "Justine",
        "email": "justine.dupuis@exemple.com",
        "roles": ["ANIMATEUR_JEUNESSE"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Jeunesse"],
        "pole_names": ["Enfants"],
    },
    {
        "nom": "Roussel",
        "prenom": "Dylan",
        "email": "dylan.roussel@exemple.com",
        "roles": ["ANIMATEUR_JEUNESSE"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Jeunesse"],
        "pole_names": ["Ados"],
    },
    {
        "nom": "Henry",
        "prenom": "Melanie",
        "email": "melanie.henry@exemple.com",
        "roles": ["ANIMATEUR_JEUNESSE"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Jeunesse"],
        "pole_names": ["Enfants"],
    },
    # ── Jeunesse — Toulouse (3) ─────────────────────────────────────────────
    {
        "nom": "Blanc",
        "prenom": "Axel",
        "email": "axel.blanc@exemple.com",
        "roles": ["ANIMATEUR_JEUNESSE"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Jeunesse"],
        "pole_names": ["Ados"],
    },
    {
        "nom": "Meyer",
        "prenom": "Chloe",
        "email": "chloe.meyer@exemple.com",
        "roles": ["ANIMATEUR_JEUNESSE"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Jeunesse"],
        "pole_names": ["Ados"],
    },
    {
        "nom": "Bernardin",
        "prenom": "Laura",
        "email": "laura.bernardin@exemple.com",
        "roles": ["ANIMATEUR_JEUNESSE"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Jeunesse"],
        "pole_names": ["Enfants"],
    },
    # ── Enseignement — Paris (3) ────────────────────────────────────────────
    {
        "nom": "Colin",
        "prenom": "Benjamin",
        "email": "benjamin.colin@exemple.com",
        "roles": ["ENSEIGNANT"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Enseignement"],
        "pole_names": ["École du Dimanche"],
    },
    {
        "nom": "Muller",
        "prenom": "Helene",
        "email": "helene.muller@exemple.com",
        "roles": ["ENSEIGNANT"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Enseignement"],
        "pole_names": ["École du Dimanche"],
    },
    {
        "nom": "Legrand",
        "prenom": "Samuel",
        "email": "samuel.legrand@exemple.com",
        "roles": ["ENSEIGNANT"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Enseignement"],
        "pole_names": ["École du Dimanche"],
    },
    # ── Enseignement — Toulouse (2) ─────────────────────────────────────────
    {
        "nom": "Picard",
        "prenom": "Estelle",
        "email": "estelle.picard@exemple.com",
        "roles": ["ENSEIGNANT"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Enseignement"],
        "pole_names": ["École du Dimanche"],
    },
    {
        "nom": "Vasseur",
        "prenom": "Aurelien",
        "email": "aurelien.vasseur@exemple.com",
        "roles": ["ENSEIGNANT"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Enseignement"],
        "pole_names": ["École du Dimanche"],
    },
    # ── Intercession — Paris (3) ────────────────────────────────────────────
    {
        "nom": "Pires",
        "prenom": "Rachel",
        "email": "rachel.pires@exemple.com",
        "roles": ["PRIEUR"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Intercession"],
        "pole_names": ["Prière du Matin"],
    },
    {
        "nom": "Moreira",
        "prenom": "Daniel",
        "email": "daniel.moreira@exemple.com",
        "roles": ["PRIEUR"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Intercession"],
        "pole_names": ["Intercession"],
    },
    {
        "nom": "Fouquet",
        "prenom": "Martine",
        "email": "martine.fouquet@exemple.com",
        "roles": ["PRIEUR"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Intercession"],
        "pole_names": ["Prière du Matin"],
    },
    # ── Intercession — Toulouse (2) ─────────────────────────────────────────
    {
        "nom": "Santos",
        "prenom": "Esther",
        "email": "esther.santos@exemple.com",
        "roles": ["PRIEUR"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Intercession"],
        "pole_names": ["Intercession"],
    },
    {
        "nom": "Ferreira",
        "prenom": "Joseph",
        "email": "joseph.ferreira@exemple.com",
        "roles": ["PRIEUR"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Intercession"],
        "pole_names": ["Prière du Matin"],
    },
    # ── Communication — Paris (3) ───────────────────────────────────────────
    {
        "nom": "Dubois",
        "prenom": "Sarah",
        "email": "sarah.dubois@exemple.com",
        "roles": ["GRAPHISTE"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Communication"],
        "pole_names": ["Photo et Design"],
    },
    {
        "nom": "Laurent",
        "prenom": "Nicolas",
        "email": "nicolas.laurent@exemple.com",
        "roles": ["PHOTOGRAPHE"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Communication"],
        "pole_names": ["Photo et Design"],
    },
    {
        "nom": "Moreau",
        "prenom": "Julie",
        "email": "julie.moreau@exemple.com",
        "roles": ["RESEAUX_SOCIAUX"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Communication"],
        "pole_names": ["Médias Numériques"],
    },
    # ── Communication — Toulouse (1) ────────────────────────────────────────
    {
        "nom": "Adam",
        "prenom": "Maxime",
        "email": "maxime.adam@exemple.com",
        "roles": ["GRAPHISTE"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Communication"],
        "pole_names": ["Médias Numériques"],
    },
    # ── Intendance — Paris (3) ──────────────────────────────────────────────
    {
        "nom": "Benoit",
        "prenom": "Francois",
        "email": "francois.benoit@exemple.com",
        "roles": ["INTENDANT"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Intendance"],
        "pole_names": ["Logistique"],
    },
    {
        "nom": "Gautier",
        "prenom": "Marguerite",
        "email": "marguerite.gautier@exemple.com",
        "roles": ["INTENDANT"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Intendance"],
        "pole_names": ["Logistique"],
    },
    {
        "nom": "Lemaire",
        "prenom": "Victor",
        "email": "victor.lemaire@exemple.com",
        "roles": ["INTENDANT"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Intendance"],
        "pole_names": ["Logistique"],
    },
    # ── Intendance — Toulouse (2) ───────────────────────────────────────────
    {
        "nom": "Perrier",
        "prenom": "Olivier",
        "email": "olivier.perrier@exemple.com",
        "roles": ["INTENDANT"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Intendance"],
        "pole_names": ["Logistique"],
    },
    {
        "nom": "Charpentier",
        "prenom": "Nathalie",
        "email": "nathalie.charpentier@exemple.com",
        "roles": ["INTENDANT"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Intendance"],
        "pole_names": ["Logistique"],
    },
    # ── MCAD — Paris + Toulouse (4) ─────────────────────────────────────────
    {
        "nom": "Leroy",
        "prenom": "Celine",
        "email": "celine.leroy@exemple.com",
        "roles": ["DANSEUR"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["MCAD"],
        "pole_names": ["Danse"],
    },
    {
        "nom": "Vidal",
        "prenom": "Hugo",
        "email": "hugo.vidal@exemple.com",
        "roles": ["COMEDIEN"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["MCAD"],
        "pole_names": ["Théâtre"],
    },
    {
        "nom": "Marchand",
        "prenom": "Emilie",
        "email": "emilie.marchand@exemple.com",
        "roles": ["DANSEUR", "CHOREO"],
        "campus_names": CAMPUS_BOTH_LIST,
        "ministere_names": ["MCAD"],
        "pole_names": ["Danse"],
    },
    {
        "nom": "Clement",
        "prenom": "Baptiste",
        "email": "baptiste.clement@exemple.com",
        "roles": ["DANSEUR"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["MCAD"],
        "pole_names": ["Danse"],
    },
    # ── Sonorisation — Paris + Toulouse (4) ─────────────────────────────────
    {
        "nom": "Giraud",
        "prenom": "Alexis",
        "email": "alexis.giraud@exemple.com",
        "roles": ["SONORISATEUR"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Sonorisation"],
        "pole_names": ["Régie Sono"],
    },
    {
        "nom": "Barbier",
        "prenom": "Lea",
        "email": "lea.barbier@exemple.com",
        "roles": ["MIXEUR"],
        "campus_names": CAMPUS_PARIS_LIST,
        "ministere_names": ["Sonorisation"],
        "pole_names": ["Régie Sono"],
    },
    {
        "nom": "Nguyen",
        "prenom": "Kevin",
        "email": "kevin.nguyen@exemple.com",
        "roles": ["SONORISATEUR"],
        "campus_names": CAMPUS_TOULOUSE_LIST,
        "ministere_names": ["Sonorisation"],
        "pole_names": ["Régie Sono"],
    },
    {
        "nom": "Fabre",
        "prenom": "Marion",
        "email": "marion.fabre@exemple.com",
        "roles": ["MIXEUR"],
        "campus_names": CAMPUS_BOTH_LIST,
        "ministere_names": ["Sonorisation"],
        "pole_names": ["Régie Sono"],
    },
]

# ---------------------------------------------------------------------------
# ~25 indisponibilités réparties sur plusieurs membres et périodes
# ---------------------------------------------------------------------------
INDISPONIBILITES_SEED: List[IndisponibiliteData] = [
    {
        "membre_email": "marie.leclerc@exemple.com",
        "date_debut": "2026-07-01",
        "date_fin": "2026-07-14",
        "motif": "Vacances d'été",
        "validee": True,
    },
    {
        "membre_email": "jean.dupont@exemple.com",
        "date_debut": "2026-08-10",
        "date_fin": "2026-08-20",
        "motif": "Formation professionnelle",
        "validee": False,
    },
    {
        "membre_email": "marc.bonnet@exemple.com",
        "date_debut": "2026-06-15",
        "date_fin": "2026-06-22",
        "motif": "Maladie",
        "validee": True,
    },
    {
        "membre_email": "fatou.diallo@exemple.com",
        "date_debut": "2026-09-01",
        "date_fin": "2026-09-05",
        "motif": "Voyage famille",
        "validee": True,
    },
    {
        "membre_email": "nathan.renard@exemple.com",
        "date_debut": "2026-07-20",
        "date_fin": "2026-07-27",
        "motif": "Stage professionnel",
        "validee": False,
    },
    {
        "membre_email": "benjamin.colin@exemple.com",
        "date_debut": "2026-08-01",
        "date_fin": "2026-08-31",
        "motif": "Vacances estivales",
        "validee": False,
    },
    {
        "membre_email": "rachel.pires@exemple.com",
        "date_debut": "2026-06-28",
        "date_fin": "2026-07-03",
        "motif": "Conférence missionnaire",
        "validee": True,
    },
    {
        "membre_email": "sarah.dubois@exemple.com",
        "date_debut": "2026-09-15",
        "date_fin": "2026-09-20",
        "motif": "Déplacement professionnel",
        "validee": False,
    },
    {
        "membre_email": "amandine.rousseau@exemple.com",
        "date_debut": "2026-07-10",
        "date_fin": "2026-07-17",
        "motif": "Vacances",
        "validee": False,
    },
    {
        "membre_email": "thomas.mercier@exemple.com",
        "date_debut": "2026-08-05",
        "date_fin": "2026-08-12",
        "motif": "Maladie",
        "validee": True,
    },
    {
        "membre_email": "awa.sow@exemple.com",
        "date_debut": "2026-07-25",
        "date_fin": "2026-08-02",
        "motif": "Voyage en famille",
        "validee": False,
    },
    {
        "membre_email": "sophie.martin@exemple.com",
        "date_debut": "2026-06-20",
        "date_fin": "2026-06-25",
        "motif": "Examens universitaires",
        "validee": True,
    },
    {
        "membre_email": "kevin.perrin@exemple.com",
        "date_debut": "2026-09-10",
        "date_fin": "2026-09-14",
        "motif": "Formation technique",
        "validee": False,
    },
    {
        "membre_email": "rose.ndiaye@exemple.com",
        "date_debut": "2026-07-01",
        "date_fin": "2026-07-10",
        "motif": "Vacances",
        "validee": True,
    },
    {
        "membre_email": "florent.morel@exemple.com",
        "date_debut": "2026-08-15",
        "date_fin": "2026-08-25",
        "motif": "Congés annuels",
        "validee": False,
    },
    {
        "membre_email": "cecile.aubert@exemple.com",
        "date_debut": "2026-06-30",
        "date_fin": "2026-07-07",
        "motif": "Repos médical",
        "validee": False,
    },
    {
        "membre_email": "dylan.roussel@exemple.com",
        "date_debut": "2026-09-01",
        "date_fin": "2026-09-10",
        "motif": "Stage scolaire",
        "validee": False,
    },
    {
        "membre_email": "estelle.picard@exemple.com",
        "date_debut": "2026-07-15",
        "date_fin": "2026-07-28",
        "motif": "Vacances",
        "validee": True,
    },
    {
        "membre_email": "esther.santos@exemple.com",
        "date_debut": "2026-08-20",
        "date_fin": "2026-08-30",
        "motif": "Voyage missionnaire",
        "validee": True,
    },
    {
        "membre_email": "nicolas.laurent@exemple.com",
        "date_debut": "2026-07-05",
        "date_fin": "2026-07-12",
        "motif": "Séjour à l'étranger",
        "validee": False,
    },
    {
        "membre_email": "ibrahim.coulibaly@exemple.com",
        "date_debut": "2026-06-22",
        "date_fin": "2026-06-28",
        "motif": "Maladie",
        "validee": True,
    },
    {
        "membre_email": "chloe.meyer@exemple.com",
        "date_debut": "2026-08-01",
        "date_fin": "2026-08-15",
        "motif": "Camp jeunesse",
        "validee": True,
    },
    {
        "membre_email": "pierre.bernard@exemple.com",
        "date_debut": "2026-07-20",
        "date_fin": "2026-07-31",
        "motif": "Vacances",
        "validee": False,
    },
    {
        "membre_email": "lucie.petit@exemple.com",
        "date_debut": "2026-09-05",
        "date_fin": "2026-09-12",
        "motif": "Formation musicale",
        "validee": False,
    },
    {
        "membre_email": "maxime.adam@exemple.com",
        "date_debut": "2026-08-10",
        "date_fin": "2026-08-18",
        "motif": "Conférence design",
        "validee": False,
    },
]
